### ISSUE TITLE
Amit Sanjay Idea: User generated content and check

### ISSUE THREAD

**Issue by dnemesisd** [vikasdummy/kashmiriDictionaryIssueTracker#21]
Currently the process of checking words from the team is tedious. And it can get very subjective.  Instead let users decide what meaning a word has. 

Solution: Amit Sanjay
1. let users enter the words meanings or answers2
2. Have a admin page to control the input (i.e a check to see if the words are accurate or not)

Omesh addition:
How about lets keep the dictionary meaning separate from user generated meaning.
Have a rating system with points from 1- 5 for users to give marks to the accuracy of meaning.

**Comment by vikasdummy** [comment]
a word can have multiple meanings. all meanings need be addded .

we should not trim or dilute down information.

only format needs to be checked by human eye lie removing Siv(12,212) ET(211,34)
or page numbers -- 232 --

That also because these books referenced can not be found now. Nay information is valuable and must be given to the user.
